server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
#          让gateway通过服务发现找到其他组件
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
#            - After=2010-01-20T17:42:47.789-07:00[America/Denver]
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#            - PreLog=a, b

management:
  endpoints:
    web:
      exposure:
        include: gateway

